# Generated by Django 6.0.6 on 2026-06-30 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("libreria", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="libro",
            name="isbn",
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
    ]
